/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Auto": {                                        "en": "Auto",                                            "de": "Auto",                                            "ru": "Автоматически",                                   "pt": "Auto",                                            "nl": "Auto",                                            "fr": "Auto",                                            "it": "Auto",                                            "es": "Auto"},
    "Manual": {                                      "en": "Manual",                                          "de": "Manual",                                          "ru": "Вручную",                                         "pt": "Manual",                                          "nl": "Met de hand",                                     "fr": "Manuel",                                          "it": "Manuale",                                         "es": "Manual"},
    "My select": {                                   "en": "My select",                                       "de": "Mein Auswahl",                                    "pt": "Meu selecionado",                                 "nl": "Mijn select",                                     "fr": "Mon choix",                                       "it": "La mia selezione",                                "es": "Mi seleccion"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "При сохранении настроек адаптера он сразу же перезапускается", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato"},
    "template adapter settings": {                   "en": "template adapter settings",                       "de": "Beispiel",                                        "ru": "Пример",                                          "pt": "configurações do adaptador de modelo",            "nl": "sjabloon-adapterinstellingen",                    "fr": "paramètres de l'adaptateur de modèle",            "it": "impostazioni dell'adattatore del modello",        "es": "configuración del adaptador de plantilla"},
    "test1": {                                       "en": "Test 1",                                          "pt": "Teste 1",                                         "nl": "Test 1",                                          "fr": "Test 1",                                          "it": "Test 1",                                          "es": "Prueba 1"},
    "test2": {                                       "en": "Test 2",                                          "pt": "Teste 2",                                         "nl": "Test 2",                                          "fr": "Test 2",                                          "it": "Test 2",                                          "es": "Prueba 2"},
    "Mapping rules": {                               "de": "Mapping-Regeln",                                  "ru": "Правила преобразования"},
    "Add rule: ": {                                  "de": "Regel hinzufügen: ",                              "ru": "Добавить новое правило: "},
    "Rule name": {                                   "de": "Regelname",                                       "ru": "Имя правила"},
    "Old state": {                                   "de": "Alter Zustand",                                   "ru": "Старое значение"},
    "New state": {                                   "de": "Neuer Staat",                                     "ru": "Новое значение"},
    "Operations": {                                  "de": "Operationen",                                     "ru": "Операции"},
    "ID": {                                          "de": "ID",                                              "ru": "ID"},
    "Input": {                                       "de": "Eingang",                                         "ru": "Откуда копировать"},
    "Output": {                                      "de": "Ausgabe",                                         "ru": "Куда копировать"},
    "Input and output": {                            "de": "Eingabe und Ausgabe",                             "ru": "Двустороннее копирование"},
    "Rule": {                                        "de": "Regel",                                           "ru": "Правило"},
    "Corr.": {                                      "de": "Korrektur",                                       "ru": "Коррекция"},
    "Is on?": {                                     "de": "Aktiviert",                                       "ru": "Включено"},
    "Ignore Ack": {                                  "de": "Ignor. Ack",                                      "ru": "Игнор. Ack"},
    "Add object: ": {                                "de": "Objekt hinzufügen: ",                             "ru": "Добавить объект: "},
    "Active rules": {                                "de": "Aktive Regeln",                                   "ru": "Активные правила"},
};